import = [
  "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
]

[bell]
animation = "EaseOutExpo"
duration = 0

[window]
decorations = "Full"
opacity = 0.8
blur = true

[font]
normal.family = "BlexMono Nerd Font Mono"
size = 18
normal.style = "Italic"

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Block"

[terminal]
osc52 = "CopyPaste"

